apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo # or specify other ns if you want
resources:
- configmap.yaml
- notification-generator.yaml
- notification-worker.yaml
- topic.yaml
- scaledobject.yaml