apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: notification-worker-scaler
spec:
  scaleTargetRef:
    name: notification-worker
  minReplicaCount: 1
  maxReplicaCount: 12
  cooldownPeriod: 30
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: demo-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
      consumerGroup: notification-processors
      topic: notification-events
      lagThreshold: "10"